# Generated by Django 5.1.6 on 2025-03-05 19:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_tournament'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='P1score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='P2score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Player2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='FinalMatch',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='Semifinal1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='Semifinal2',
        ),
        migrations.AddField(
            model_name='match',
            name='is_multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(related_name='matches', to='api.match'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_profiles', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_profiles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('player1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_id', to='api.userprofile')),
                ('player2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_id', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GoalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_corners', models.PositiveIntegerField()),
                ('ball_duration', models.DurationField()),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
