# Use the latest LTS version of Node.js
FROM node:22-alpine
 
# Set the working directory inside the container
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package.json and package-lock.json
COPY package*.json pnpm-lock.yaml ./

# Configurer le cache PNPM
RUN pnpm config set store-dir .pnpm-store

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of your application files
COPY . .
 
# Expose the port your app runs on
EXPOSE 3000
 
# Serve the built React app
CMD ["pnpm",  "start"]
