GAME_SETTINGS = {
    'CANVAS_WIDTH': 900,
    'CANVAS_HEIGHT': 700,
    'PADDLE_WIDTH': 15,
    'PADDLE_HEIGHT': 90,
    'INITIAL_BALL_SPEED': 1,
    'MAX_BALL_SPEED': 12,
    'BALL_RADIUS': 10,
    'WINNING_SCORE': 1,
    'PADDLE_SPEED': 8,
    'PADDLE_MARGIN': 20
}
